default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['database_username'] || postgres %>
  password: <%= ENV['database_password'] || root %>
  pool: 5

development:
  <<: *default
  database: geolocation_development


test:
  <<: *default
  database: geolocation_test