default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Saikat1997
  pool: 5

development:
  <<: *default
  database: geolocation_development


test:
  <<: *default
  database: geolocation_test